// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdj0DJsQmvz5QlA1LJT5ygg5kXWIU_BRA',
    appId: '1:405216184022:web:2bd671f25009653df46b77',
    messagingSenderId: '405216184022',
    projectId: 'onboarding-screen-f4563',
    authDomain: 'onboarding-screen-f4563.firebaseapp.com',
    storageBucket: 'onboarding-screen-f4563.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4fxoDepuY6hfHOqcvk9LwMYRvOxEfqZQ',
    appId: '1:405216184022:android:ebd1e17f33104016f46b77',
    messagingSenderId: '405216184022',
    projectId: 'onboarding-screen-f4563',
    storageBucket: 'onboarding-screen-f4563.appspot.com',
  );
}
